import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { sitesRouter } from "~/server/api/routers/sites";
import { api } from "~/utils/api";
import { type NextPage } from "next";

const ModDash = () => {
  const { data, isLoading: sitesLoading } = api.sites.getAll.useQuery();
  if (sitesLoading) return <div>Loading sites</div>;

  return (
    <div>
      {data?.map((content) => (
        <div key={content.id}>
          <Image
            src={`/api/og?title=${content.name}`}
            width={500}
            height={500}
            alt={`${content.name} image`}
          />
        </div>
      ))}
    </div>
  );
};

const Home: NextPage = () => {
  const { user, isSignedIn, isLoaded: userLoaded } = useUser();

  if (!userLoaded) return <div />;

  console.log(user?.id);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {!!isSignedIn && <SignOutButton />}
          {!isSignedIn && <SignInButton />}
        </div>
        <div>
          <ModDash />
        </div>
      </main>
    </>
  );
};

export default Home;
